### PR TITLE
Don't include timestamp in log output & remove corrupt CPTV files

### LINKED ISSUE #12: Delete corrupt CPTV files
If a CPTV file fails to parse, delete it. This can happen if the recorder was interrupted while writing out a file. Not doing this causes the uploader to get stuck trying to handle the same file over and over.

### LINKED ISSUE #13: Don't include timestamps in output
systemd already adds timestamps so there's no need to do it twice

### PR DESCRIPTION
**Pull request by CameronRP**
closes #13 
closes #12

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -103,7 +105,8 @@ func uploadFile(api *CacophonyAPI, filename string) error {
 
 	info, err := extractCPTVInfo(filename)
 	if err != nil {
-		return err
+		log.Println("failed to extract CPTV info from file")
```
Comment (mjs) [inline main.go]: perhaps mention that the file is being removed?

**Review by mjs — APPROVED** [review]
Looks good. 

I don't know if putting `closes #N` in the title line of the commit works. Usually you'd put it in the commit message body.
